### ISSUE TITLE
Querido Diário: Tecnologias na Educação

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/querido-diario-comunidade#38]
### Descrição
O objetivo do projeto é permitir o monitoramento de programas, aquisições e outras ações realizadas por municípios que envolvem tecnologias na área educacional.

Para isso, um filtro temático deve ser adicionado ao processamento, o tema deve ser buscável na API e na interface web e também deve ser criado um mecanismo configurável de envio de alertas por email.

### Tarefas
- [x] Desenvolver processamento de filtro temático
  - https://github.com/okfn-brasil/querido-diario-data-processing/pull/30
- [x] Desenvolver backend para gestão de usuários e alertas
  - [Repositório de backend](https://github.com/okfn-brasil/querido-diario-backend)
- [x] Adicionar página na plataforma do QD
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/108
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/111

**Comment by giuliocc** [comment]
### Descrição
O objetivo do projeto é permitir o monitoramento de programas, aquisições e outras ações realizadas por municípios que envolvem tecnologias na área educacional.

Para isso, um filtro temático deve ser adicionado ao processamento, o tema deve ser buscável na API e na interface web e também deve ser criado um mecanismo configurável de envio de alertas por email.

### Objetivos
- [x] Desenvolver processamento de filtro temático
  - https://github.com/okfn-brasil/querido-diario-data-processing/pull/30
- [x] Desenvolver backend para gestão de usuários e alertas
  - [Repositório de backend](https://github.com/okfn-brasil/querido-diario-backend)
- [x] Adicionar página na plataforma do QD
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/108
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/111

### Como contribuir
_Este item já foi finalizado mas sua contribuição é bem vinda em qualquer outro item do [Roadmap](https://github.com/orgs/okfn-brasil/projects/14/views/1)._

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
Description
The project's objective is to allow the monitoring of programs, acquisitions and other actions carried out by municipalities that involve technologies in the educational area.

For this, a thematic filter must be added to the processing, the theme must be searchable in the API and in the web interface and a configurable mechanism for sending alerts by email must also be created.

Goals
 Develop thematic filter processing
https://github.com/okfn-brasil/querido-diario-data-processing/pull/30
 Develop backend for managing users and alerts
[Backend repository](https://github.com/okfn-brasil/querido-diario-backend)
 Add page on QD platform
https://github.com/okfn-brasil/querido-diario-frontend/pull/108
https://github.com/okfn-brasil/querido-diario-frontend/pull/111
how to contribute
This item has already been finalized but your contribution is welcome on any other item on [Roadmap](https://github.com/orgs/okfn-brasil/projects/14/views/1).

**Comment by giuliocc** [comment]
### Descrição
O objetivo do projeto é permitir o monitoramento de programas, aquisições e outras ações realizadas por municípios que envolvem tecnologias na área educacional.

Para isso, um filtro temático deve ser adicionado ao processamento, o tema deve ser buscável na API e na interface web e também deve ser criado um mecanismo configurável de envio de alertas por email.

### Objetivos
- [x] Desenvolver processamento de filtro temático
  - https://github.com/okfn-brasil/querido-diario-data-processing/pull/30
- [x] Desenvolver backend para gestão de usuários e alertas
  - [Repositório de backend](https://github.com/okfn-brasil/querido-diario-backend)
- [x] Adicionar página na plataforma do QD
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/108
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/111

### Como contribuir
_Este item já foi finalizado mas sua contribuição é bem vinda em qualquer outro item do [Roadmap](https://github.com/orgs/okfn-brasil/projects/14/views/1)._

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### Description
The project's objective is to allow the monitoring of programs, acquisitions and other actions carried out by municipalities that involve technologies in the educational area.

For this, a thematic filter must be added to the processing, the theme must be searchable in the API and in the web interface and a configurable mechanism for sending alerts by email must also be created.

### Goals
- [x] Develop thematic filter processing
  - https://github.com/okfn-brasil/querido-diario-data-processing/pull/30
- [x] Develop backend for managing users and alerts
  - [Backend repository](https://github.com/okfn-brasil/querido-diario-backend)
- [x] Add page on the QD platform
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/108
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/111

### How to contribute
_This item has already been finalized but your contribution is welcome in any other item on [Roadmap](https://github.com/orgs/okfn-brasil/projects/14/views/1)._
