### ISSUE TITLE
Base para segmentação de diários de associações de municípios

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario-comunidade#42]
### Descrição
Como descrito em mais detalhes no blogpost ["Conheça os desafios de raspagem do Querido Diário"](https://queridodiario.ok.org.br/blog/post/28), diários de associações de municípios não são atualmente compatíveis com o Querido Diário por conterem conteúdo de diversos municípios no mesmo documento e assim impossibilitar o filtro de conteúdo por município ao realizar buscas textuais no documento processado.

O objetivo aqui é continuar o [esforço iniciado no programa "Querido Diário nas Universidades"](https://queridodiario.ok.org.br/blog/post/23) por um grupo de iniciação científica do Instituto Federal de Alagoas (IFAL) de segmentar o diário da Associação dos Municípios Alagoanos (AMA).

O escopo inicial é adequar o [código desenvolvido pelo grupo do IFAL](https://github.com/exoonero/extrator) ao [pipeline de processamento de dados do QD](https://github.com/okfn-brasil/querido-diario-data-processing/). Assim, estabeleceremos o padrão que será utilizado como base para integrar outras associações municipais e diários estaduais (que possuem cadernos de publicações municipais) futuramente. 

### Objetivos
- [X] Familiarização com processamento do [exoonero](https://github.com/exoonero/extrator)
- [ ] Mapeamento do fluxo de dados raspadores -> data-processing
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/42
- [x] Implementação em ambiente de homologação
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/40
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/43
- [x] Implementação em produção
  - https://github.com/okfn-brasil/querido-diario-data-processing/pull/64

### Como contribuir

_Este item já foi finalizado mas sua contribuição é bem vinda em qualquer outro item do [Roadmap](https://github.com/orgs/okfn-brasil/projects/14/views/1)._

Esta atividade foi desenvolvida dentro do escopo da Trilha de Segmentadores do Grupo de Trabalho para Processamento de Dados (vigente no segundo semestre de 2023). O andamento da trilha foi gerenciado pelo [quadro](https://github.com/orgs/okfn-brasil/projects/29/views/1), com coordenação de @jefersonalves e atuação de @winzen e @alex-custodio.

**Comment by ogecece** [comment]
### Descrição
Como descrito em mais detalhes no blogpost ["Conheça os desafios de raspagem do Querido Diário"](https://queridodiario.ok.org.br/blog/post/28), diários de associações de municípios não são atualmente compatíveis com o Querido Diário por conterem conteúdo de diversos municípios no mesmo documento e assim impossibilitar o filtro de conteúdo por município ao realizar buscas textuais no documento processado.

O objetivo aqui é continuar o [esforço iniciado no programa "Querido Diário nas Universidades"](https://queridodiario.ok.org.br/blog/post/23) por um grupo de iniciação científica do Instituto Federal de Alagoas (IFAL) de segmentar o diário da Associação dos Municípios Alagoanos (AMA).

O escopo inicial é adequar o [código desenvolvido pelo grupo do IFAL](https://github.com/exoonero/extrator) ao [pipeline de processamento de dados do QD](https://github.com/okfn-brasil/querido-diario-data-processing/). Assim, estabeleceremos o padrão que será utilizado como base para integrar outras associações municipais e diários estaduais (que possuem cadernos de publicações municipais) futuramente. 

### Objetivos
- [X] Familiarização com processamento do [exoonero](https://github.com/exoonero/extrator)
- [ ] Mapeamento do fluxo de dados raspadores -> data-processing
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/42
- [ ] Implementação em ambiente de homologação
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/40
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/43
- [ ] Implementação em produção

### Como contribuir
Esta atividade está sendo desenvolvida dentro do escopo da Trilha de Segmentadores do Grupo de Trabalho para Processamento de Dados (vigente no segundo semestre de 2023). Você pode acompanhar o andamento da trilha pelo [quadro](https://github.com/orgs/okfn-brasil/projects/29/views/1) e também pode entrar em contato com quem está coordenando a trilha (@jefersonalves) e poderá te dar direcionamentos sobre como participar pelo [Discord da OKBR](https://go.ok.org.br/discord) no canal #qd-backend.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### Description
As described in more detail in the blogpost ["Learn about the challenges of scraping Querido Diario"](https://queridodiario.ok.org.br/blog/post/28), municipal association diaries are not currently compatible with Querido Diário because they contain content from different municipalities in the same document and thus make it impossible to filter content by municipality when carrying out textual searches in the processed document.

The objective here is to continue the [effort started in the "Querido Diário nas Universidades" program](https://queridodiario.ok.org.br/blog/post/23) by a scientific initiation group from the Federal Institute of Alagoas (IFAL ) to segment the diary of the Association of Municipalities of Alagoas (AMA).

The initial scope is to adapt the [code developed by the IFAL group](https://github.com/exonero/extrator) to the [QD data processing pipeline](https://github.com/okfn-brasil/ darling-diary-data-processing/). In this way, we will establish the standard that will be used as a basis to integrate other municipal associations and state newspapers (which have municipal publications sections) in the future.

### Goals
- [X] Familiarization with [exonero] processing (https://github.com/exonero/extrator)
- [ ] Scraper data flow mapping -> data-processing
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/42
- [ ] Implementation in an approval environment
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/40
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/43
- [ ] Implementation in production

### How to contribute
This activity is being developed within the scope of the Segmenter Track of the Data Processing Working Group (effective in the second half of 2023). You can follow the progress of the trail through [board](https://github.com/orgs/okfn-brasil/projects/29/views/1) and you can also get in touch with whoever is coordinating the trail (@jefersonalves) and can give you directions on how to participate via [OKBR Discord](https://go.ok.org.br/discord) on the #qd-backend channel.

**Comment by ogecece** [comment]
### Descrição
Como descrito em mais detalhes no blogpost ["Conheça os desafios de raspagem do Querido Diário"](https://queridodiario.ok.org.br/blog/post/28), diários de associações de municípios não são atualmente compatíveis com o Querido Diário por conterem conteúdo de diversos municípios no mesmo documento e assim impossibilitar o filtro de conteúdo por município ao realizar buscas textuais no documento processado.

O objetivo aqui é continuar o [esforço iniciado no programa "Querido Diário nas Universidades"](https://queridodiario.ok.org.br/blog/post/23) por um grupo de iniciação científica do Instituto Federal de Alagoas (IFAL) de segmentar o diário da Associação dos Municípios Alagoanos (AMA).

O escopo inicial é adequar o [código desenvolvido pelo grupo do IFAL](https://github.com/exoonero/extrator) ao [pipeline de processamento de dados do QD](https://github.com/okfn-brasil/querido-diario-data-processing/). Assim, estabeleceremos o padrão que será utilizado como base para integrar outras associações municipais e diários estaduais (que possuem cadernos de publicações municipais) futuramente. 

### Objetivos
- [X] Familiarização com processamento do [exoonero](https://github.com/exoonero/extrator)
- [ ] Mapeamento do fluxo de dados raspadores -> data-processing
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/42
- [x] Implementação em ambiente de homologação
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/40
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/43
- [x] Implementação em produção
  - https://github.com/okfn-brasil/querido-diario-data-processing/pull/64

### Como contribuir

_Este item já foi finalizado mas sua contribuição é bem vinda em qualquer outro item do [Roadmap](https://github.com/orgs/okfn-brasil/projects/14/views/1)._

Esta atividade foi desenvolvida dentro do escopo da Trilha de Segmentadores do Grupo de Trabalho para Processamento de Dados (vigente no segundo semestre de 2023). O andamento da trilha foi gerenciado pelo [quadro](https://github.com/orgs/okfn-brasil/projects/29/views/1), com coordenação de @jefersonalves e atuação de @winzen e @alex-custodio.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### Description
As described in more detail in the blogpost ["Learn about the challenges of scraping Querido Diario"](https://queridodiario.ok.org.br/blog/post/28), municipal association diaries are not currently compatible with Querido Diário because they contain content from different municipalities in the same document and thus make it impossible to filter content by municipality when carrying out textual searches in the processed document.

The objective here is to continue the [effort started in the "Querido Diário nas Universidades" program](https://queridodiario.ok.org.br/blog/post/23) by a scientific initiation group from the Federal Institute of Alagoas (IFAL ) to segment the diary of the Association of Municipalities of Alagoas (AMA).

The initial scope is to adapt the [code developed by the IFAL group](https://github.com/exonero/extrator) to the [QD data processing pipeline](https://github.com/okfn-brasil/ darling-diary-data-processing/). In this way, we will establish the standard that will be used as a basis to integrate other municipal associations and state newspapers (which have municipal publications sections) in the future.

### Goals
- [X] Familiarization with [exonero] processing (https://github.com/exonero/extrator)
- [ ] Scraper data flow mapping -> data-processing
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/42
- [x] Implementation in an approval environment
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/40
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/43
- [x] Implementation in production
  - https://github.com/okfn-brasil/querido-diario-data-processing/pull/64

### How to contribute

_This item has already been finalized but your contribution is welcome on any other item on the [Roadmap](https://github.com/orgs/okfn-brasil/projects/14/views/1)._

This activity was developed within the scope of the Segmenter Track of the Data Processing Working Group (effective in the second half of 2023). The progress of the trail was managed by [cadre](https://github.com/orgs/okfn-brasil/projects/29/views/1), coordinated by @jefersonalves and acting by @winzen and @alex-custodio.
