### ISSUE TITLE
Funcionalidades de "Blog" e "Casos de Sucesso"

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/querido-diario-comunidade#53]
### Descrição
Breve descrição da atividade, sua importância para o Querido Diário e o que seria necessário para completá-la.

Para tornar a produção e divulgação de conteúdo pelo projeto mais centralizada (evitando posts no blog da OKBR, por exemplo) um Blog do projeto deveria ser criado. Isso já foi mapeado nessa issue: https://github.com/okfn-brasil/querido-diario-frontend/issues/32

E para destaque de materiais externos que envolvam o Querido Diário, uma seção de "Casos de sucesso" também seria bem útil. Isso também já foi mapeado nessa outra issue: https://github.com/okfn-brasil/querido-diario-frontend/issues/33

### Objetivos
- [X] Adicionar página de Blog
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/108
- [X] Adicionar seção de "Casos de sucesso"
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/108

### Como contribuir
_Este item já foi finalizado mas sua contribuição é bem vinda em qualquer outro item do [Roadmap](https://github.com/orgs/okfn-brasil/projects/14/views/1)._

**Comment by giuliocc** [comment]
### Descrição
Breve descrição da atividade, sua importância para o Querido Diário e o que seria necessário para completá-la.

Para tornar a produção e divulgação de conteúdo pelo projeto mais centralizada (evitando posts no blog da OKBR, por exemplo) um Blog do projeto deveria ser criado. Isso já foi mapeado nessa issue: https://github.com/okfn-brasil/querido-diario-frontend/issues/32

E para destaque de materiais externos que envolvam o Querido Diário, uma seção de "Casos de sucesso" também seria bem útil. Isso também já foi mapeado nessa outra issue: https://github.com/okfn-brasil/querido-diario-frontend/issues/33

### Objetivos
- [X] Adicionar página de Blog
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/108
- [X] Adicionar seção de "Casos de sucesso"
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/108

### Como contribuir
_Este item já foi finalizado mas sua contribuição é bem vinda em qualquer outro item do [Roadmap](https://github.com/orgs/okfn-brasil/projects/14/views/1)._

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### Description
Brief description of the activity, its importance to Querido Diário and what it would take to complete it.

To make the production and dissemination of content by the project more centralized (avoiding posts on the OKBR blog, for example) a Project Blog should be created. This has already been mapped in this issue: https://github.com/okfn-brasil/querido-diario-frontend/issues/32

And to highlight external materials involving Querido Diário, a "Success Stories" section would also be very useful. This has also been mapped in this other issue: https://github.com/okfn-brasil/querido-diario-frontend/issues/33

### Goals
- [X] Add Blog Page
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/108
- [X] Add "Success Stories" section
  - https://github.com/okfn-brasil/querido-diario-frontend/pull/108

### How to contribute
_This item has already been finalized but your contribution is welcome in any other item on [Roadmap](https://github.com/orgs/okfn-brasil/projects/14/views/1)._
