### ISSUE TITLE
Documentação bilíngue

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario-comunidade#55]
### Descrição
Como o Querido Diário é um projeto principalmente brasileiro e por muitos brasileiros não se sentirem confortáveis com o inglês ter o português como o idioma principal do projeto remove uma barreira inicial importante para muitas pessoas. No entanto, por ser um projeto de inovação cívica relevante e já ter tido contribuições internacionais, o idioma inglês também deveria estar presente no projeto. Principalmente nas suas documentações mais relevantes como a [documentação técnica](https://docs.queridodiario.ok.org.br/) e arquivos de documentação dos repositórios.

O site do projeto também deveria ter versões em diferentes idiomas mas isso pode ser priorizado em uma etapa futura.

### Objetivos
- [ ] Tradução do [site](https://queridodiario.ok.org.br/)
  - https://github.com/okfn-brasil/querido-diario-frontend/issues/163
- [ ] Traduções da [documentação técnica](https://docs.queridodiario.ok.org.br/)
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/69
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/68
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/67
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/66
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/65
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/97
- [ ] Traduções do [querido-diario-comunidade](https://github.com/okfn-brasil/querido-diario-comunidade)
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/16
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/33
- [x] Traduções do [querido-diario](https://github.com/okfn-brasil/querido-diario)
  - https://github.com/okfn-brasil/querido-diario/pull/605
- [ ] Traduções do [querido-diario-data-processing](https://github.com/okfn-brasil/querido-diario-data-processing)
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/45
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/46
- [ ] Traduções do [querido-diario-frontend](https://github.com/okfn-brasil/querido-diario-frontend)
  - https://github.com/okfn-brasil/querido-diario-frontend/issues/180
  - https://github.com/okfn-brasil/querido-diario-frontend/issues/181
- [ ] Traduções do [querido-diario-backend](https://github.com/okfn-brasil/querido-diario-backend)
  - https://github.com/okfn-brasil/querido-diario-backend/issues/2
  - https://github.com/okfn-brasil/querido-diario-backend/issues/3
- [ ] Traduções do [querido-diario-api](https://github.com/okfn-brasil/querido-diario-api)
  - https://github.com/okfn-brasil/querido-diario-api/issues/61
  - https://github.com/okfn-brasil/querido-diario-api/issues/62
- [ ] Traduções do [querido-diario-toolbox](https://github.com/okfn-brasil/querido-diario-toolbox)
  - https://github.com/okfn-brasil/querido-diario-toolbox/issues/48
  - https://github.com/okfn-brasil/querido-diario-toolbox/issues/49
- [ ] Traduções do [querido-diario-api-wrapper](https://github.com/okfn-brasil/querido-diario-api-wrapper)
  - https://github.com/okfn-brasil/querido-diario-api-wrapper/issues/5
  - https://github.com/okfn-brasil/querido-diario-api-wrapper/issues/6
- [ ] Traduções do [querido-diario-infra](https://github.com/okfn-brasil/querido-diario-infra)
  - Issue de tradução

### Como contribuir
A documentação está sendo melhorada como destacado em #41. Após a finalização dessas melhorias, issues de tradução estão sendo criadas e devem estar listadas acima (caso encontre alguma que já tenha sido criada não esteja mapeada, comente aqui mesmo) e podem ser trabalhadas.

**Comment by giuliocc** [comment]
### Descrição
Como o Querido Diário é um projeto principalmente brasileiro e por muitos brasileiros não se sentirem confortáveis com o inglês ter o português como o idioma principal do projeto remove uma barreira inicial importante para muitas pessoas. No entanto, por ser um projeto de inovação cívica relevante e já ter tido contribuições internacionais, o idioma inglês também deveria estar presente no projeto. Principalmente nas suas documentações mais relevantes como a [documentação técnica](https://docs.queridodiario.ok.org.br/) e arquivos de documentação dos repositórios.

O site do projeto também deveria ter versões em diferentes idiomas mas isso pode ser priorizado em uma etapa futura.

### Objetivos
- [ ] Traduções da [documentação técnica](https://docs.queridodiario.ok.org.br/)
  - Issue de tradução
- [ ] Traduções do [querido-diario-comunidade](https://github.com/okfn-brasil/querido-diario-comunidade)
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/16
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/33
- [ ] Traduções do [querido-diario](https://github.com/okfn-brasil/querido-diario)
  - Issue de tradução
- [ ] Traduções do [querido-diario-data-processing](https://github.com/okfn-brasil/querido-diario-data-processing)
  - Issue de tradução
- [ ] Traduções do [querido-diario-frontend](https://github.com/okfn-brasil/querido-diario-frontend)
  - Issue de tradução
- [ ] Traduções do [querido-diario-backend](https://github.com/okfn-brasil/querido-diario-backend)
  - Issue de tradução
- [ ] Traduções do [querido-diario-api](https://github.com/okfn-brasil/querido-diario-api)
  - Issue de tradução
- [ ] Traduções do [querido-diario-toolbox](https://github.com/okfn-brasil/querido-diario-toolbox)
  - Issue de tradução
- [ ] Traduções do [querido-diario-api-wrapper](https://github.com/okfn-brasil/querido-diario-api-wrapper)
  - Issue de tradução
- [ ] Traduções do [querido-diario-infra](https://github.com/okfn-brasil/querido-diario-infra)
  - Issue de tradução

### Como contribuir
A documentação está sendo melhorada como destacado em #41. Após a finalização dessas melhorias, issues de tradução estão sendo criadas e devem estar listadas acima (caso encontre alguma que já tenha sido criada não esteja mapeada, comente aqui mesmo) e podem ser trabalhadas.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### Description
As Querido Diário is a primarily Brazilian project and because many Brazilians are not comfortable with English, having Portuguese as the main language of the project removes an important initial barrier for many people. However, as it is a relevant civic innovation project and has already had international contributions, the English language should also be present in the project. Mainly in its most relevant documentation such as the [technical documentation](https://docs.queridodiario.ok.org.br/) and documentation files of the repositories.

The project website should also have versions in different languages ​​but this can be prioritized in a future step.

### Goals
- [ ] Translations of [technical documentation](https://docs.queridodiario.ok.org.br/)
  - Translation issue
- [ ] Translations from [querido-diario-comunidade](https://github.com/okfn-brasil/querido-diario-comunidade)
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/16
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/33
- [ ] Translations of [querido-diario](https://github.com/okfn-brasil/querido-diario)
  - Translation issue
- [ ] Translations of [querido-diario-data-processing](https://github.com/okfn-brasil/querido-diario-data-processing)
  - Translation issue
- [ ] Translations from [querido-diario-frontend](https://github.com/okfn-brasil/querido-diario-frontend)
  - Translation issue
- [ ] Translations from [querido-diario-backend](https://github.com/okfn-brasil/querido-diario-backend)
  - Translation issue
- [ ] Translations from [querido-diario-api](https://github.com/okfn-brasil/querido-diario-api)
  - Translation issue
- [ ] Translations from [querido-diario-toolbox](https://github.com/okfn-brasil/querido-diario-toolbox)
  - Translation issue
- [ ] Translations of [querido-diario-api-wrapper](https://github.com/okfn-brasil/querido-diario-api-wrapper)
  - Translation issue
- [ ] Translations from [querido-diario-infra](https://github.com/okfn-brasil/querido-diario-infra)
  - Translation issue

### How to contribute
Documentation is being improved as highlighted in #41. After the completion of these improvements, translation issues are being created and should be listed above (if you find any that have already been created and are not mapped, comment right here) and can be worked on.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### Description
As Querido Diário is a mainly Brazilian project and because many Brazilians are not comfortable with English, having Portuguese as the main language of the project removes an important initial barrier for many people. However, as it is a relevant civic innovation project and has already had international contributions, the English language should also be present in the project. Mainly in its most relevant documentation such as [technical documentation](https://docs.queridodiario.ok.org.br/) and repository documentation files.

The project website should also have versions in different languages ​​but this can be prioritized at a future stage.

### Goals
- [ ] Translation from [site](https://queridodiario.ok.org.br/)
  - Proof of concept issue of website localization
- [ ] Translations of [technical documentation](https://docs.queridodiario.ok.org.br/)
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/69
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/68
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/67
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/66
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/65
- [ ] Translations of [querido-diario-comunidade](https://github.com/okfn-brasil/querido-diario-comunidade)
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/16
  - https://github.com/okfn-brasil/querido-diario-comunidade/issues/33
- [ ] Translations of [querido-diario](https://github.com/okfn-brasil/querido-diario)
  - https://github.com/okfn-brasil/querido-diario/pull/605
- [ ] Translations of [querido-diario-data-processing](https://github.com/okfn-brasil/querido-diario-data-processing)
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/45
  - https://github.com/okfn-brasil/querido-diario-data-processing/issues/46
- [ ] Translations of [querido-diario-frontend](https://github.com/okfn-brasil/querido-diario-frontend)
  - https://github.com/okfn-brasil/querido-diario-frontend/issues/180
  - https://github.com/okfn-brasil/querido-diario-frontend/issues/181
- [ ] Translations of [querido-diario-backend](https://github.com/okfn-brasil/querido-diario-backend)
  - https://github.com/okfn-brasil/querido-diario-backend/issues/2
  - https://github.com/okfn-brasil/querido-diario-backend/issues/3
- [ ] Translations of [querido-diario-api](https://github.com/okfn-brasil/querido-diario-api)
  - https://github.com/okfn-brasil/querido-diario-api/issues/61
  - https://github.com/okfn-brasil/querido-diario-api/issues/62
- [ ] Translations of [querido-diario-toolbox](https://github.com/okfn-brasil/querido-diario-toolbox)
  - https://github.com/okfn-brasil/querido-diario-toolbox/issues/48
  - https://github.com/okfn-brasil/querido-diario-toolbox/issues/49
- [ ] Translations of [querido-diario-api-wrapper](https://github.com/okfn-brasil/querido-diario-api-wrapper)
  - https://github.com/okfn-brasil/querido-diario-api-wrapper/issues/5
  - https://github.com/okfn-brasil/querido-diario-api-wrapper/issues/6
- [ ] Translations of [querido-diario-infra](https://github.com/okfn-brasil/querido-diario-infra)
  - Translation issue

### How to contribute
Documentation is being improved as highlighted in #41. After these improvements are completed, translation issues are being created and should be listed above (if you find any that have already been created and are not mapped, comment here) and can be worked on.
